[log]
disable-timestamp = false
level = "info"
format = "text"
filename = "/tmp/robber-notification/data.log"
maxsize = 20

[etcd]
endpoints = [
	"127.0.0.1:2379",
]

[server]
host = "0.0.0.0"
port = 19091

[smtp]
path = "./scripts/smtp.json"