[log]
disable-timestamp = false
level = "info"
format = "text"
filename = "../log/data.log"
maxsize = 20

[etcd]
endpoints = [
	"127.0.0.1:2379",
]

[server]
host = "0.0.0.0"
port = 27322

[smtp]
path = "../etc/smtp.json"